#!/usr/bin/env bash
# setup-hooks.sh — wire Throughline's write-safety hooks for macOS/Linux (no Python required).
# Writes the gitignored .claude/settings.local.json and rebuilds .codex/hooks.json with the
# bash + .sh launchers. Equivalent to `python3 tools/setup-hooks.py` on Unix.
#
# If a JSON parser (python3) is present it is used for a clean merge that preserves any
# existing keys (e.g. target access). Without it, a fresh hooks-only file is written when
# none exists; if one already exists, you are told to add the hooks block (or install python3)
# so existing settings are never clobbered.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [ ! -f "$ROOT/.github/hooks/scripts/validate-immutable-paths.sh" ]; then
  echo "ERROR: Hook scripts not found. Run tools/install or tools/convert --tool shared first." >&2
  exit 1
fi

# Prefer a Python that actually runs. On Windows Git Bash, `python` is often the Store stub.
pick_python() {
  local c
  for c in python3 py python; do
    command -v "$c" >/dev/null 2>&1 || continue
    "$c" -c 'import sys' >/dev/null 2>&1 || continue
    printf '%s' "$c"
    return 0
  done
  return 1
}
if PY="$(pick_python)"; then
  exec "$PY" "$ROOT/tools/setup-hooks.py"
fi

claude_local="$ROOT/.claude/settings.local.json"
codex_path="$ROOT/.codex/hooks.json"

claude_hooks_json() {
cat <<'JSON'
{
  "hooks": {
    "PreToolUse": [
      { "matcher": "Write|Edit|MultiEdit|NotebookEdit",
        "hooks": [ { "type": "command", "command": "bash .claude/hooks/validate-immutable-paths.sh", "timeout": 10 } ] },
      { "matcher": "Bash",
        "hooks": [ { "type": "command", "command": "bash .claude/hooks/validate-bash-safety.sh", "timeout": 10 } ] }
    ],
    "PostToolUse": [
      { "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          { "type": "command", "command": "bash .claude/hooks/log-tool-use.sh", "timeout": 15 },
          { "type": "command", "command": "bash .claude/hooks/check-code-quality.sh", "timeout": 30 }
        ] }
    ]
  }
}
JSON
}

if [ -f "$claude_local" ] && [ -s "$claude_local" ]; then
  echo "WARN: $claude_local already exists and no JSON parser is available to merge safely."
  echo "      Add this 'hooks' block to it by hand (or install python3 and re-run):"
  claude_hooks_json
else
  claude_hooks_json > "$claude_local"
  echo "wrote $claude_local"
fi

cat > "$codex_path" <<'JSON'
{
  "_comment": "Generated by tools/setup-hooks.sh for macOS/Linux. Re-run after switching OS. Codex sends the same stdin JSON + exit-2 protocol; the shared .github guard scripts apply.",
  "hooks": {
    "PreToolUse": [
      { "matcher": "apply_patch|Edit|Write",
        "hooks": [ { "type": "command", "command": "bash .github/hooks/scripts/validate-immutable-paths.sh", "timeout": 10, "statusMessage": "Guarding /standards/ + /exemplars/ (read-only)" } ] },
      { "matcher": "Bash",
        "hooks": [ { "type": "command", "command": "bash .github/hooks/scripts/validate-bash-safety.sh", "timeout": 10, "statusMessage": "Blocking writes to immutable paths + git push/merge (human-only)" } ] }
    ],
    "PostToolUse": [
      { "matcher": "apply_patch|Edit|Write",
        "hooks": [
          { "type": "command", "command": "bash .github/hooks/scripts/log-tool-use.sh", "timeout": 15, "statusMessage": "Appending to wiki/log.md" },
          { "type": "command", "command": "bash .github/hooks/scripts/check-code-quality.sh", "timeout": 30, "statusMessage": "Quality lint on written files" }
        ] }
    ]
  }
}
JSON
echo "wrote $codex_path"

# Cursor: install .cursor/hooks.json from the staged template, rewritten for bash.
# Prefix bare ".github/hooks/scripts/<name>.sh" commands with "bash " so they run without +x.
cursor_dir="$ROOT/.cursor"
cursor_template="$ROOT/.throughline/adapters/generated/cursor/hooks.template.json"
if [ -d "$cursor_dir" ] && [ -f "$cursor_template" ]; then
  sed -E 's#"(\.github/hooks/scripts/[A-Za-z0-9._-]+\.sh)"#"bash \1"#g' "$cursor_template" > "$cursor_dir/hooks.json"
  echo "wrote $cursor_dir/hooks.json (fail-open until .cursor/VERIFICATION.md passes)"
fi

# Antigravity: install .agents/hooks.json from the staged template, rewritten for bash.
agents_dir="$ROOT/.agents"
ag_template="$ROOT/.throughline/adapters/generated/antigravity/hooks.template.json"
if [ -f "$ROOT/GEMINI.md" ] && [ -f "$ag_template" ]; then
  mkdir -p "$agents_dir"
  sed -E 's#"(\.github/hooks/scripts/[A-Za-z0-9._-]+\.sh)"#"bash \1"#g' "$ag_template" > "$agents_dir/hooks.json"
  echo "wrote $agents_dir/hooks.json (best-effort matchers until .agents/VERIFICATION.md passes)"
fi

# Kimi Code: install .kimi/config.toml from the staged template, rewritten for bash.
kimi_dir="$ROOT/.kimi"
kimi_template="$ROOT/.throughline/adapters/generated/kimi/hooks.template.toml"
if [ -f "$kimi_dir/AGENTS.md" ] && [ -f "$kimi_template" ]; then
  mkdir -p "$kimi_dir"
  sed -E 's#command = "\.github/hooks/scripts/([A-Za-z0-9._-]+)\.sh"#command = "bash .github/hooks/scripts/\1.sh"#g' "$kimi_template" > "$kimi_dir/config.toml"
  echo "wrote $kimi_dir/config.toml (best-effort matchers until .kimi/VERIFICATION.md passes)"
fi

[ -f "$ROOT/.github/hooks/copilot-cli.json" ] && echo "  Copilot CLI: .github/hooks/copilot-cli.json (cross-OS; no per-OS wiring needed)"
echo "Throughline hooks wired for macOS/Linux (bash + .sh)."
