# setup-hooks.ps1 — wire Throughline's write-safety hooks for Windows (no Python required).
# PowerShell has built-in JSON, so this needs nothing beyond Windows PowerShell itself.
# Writes the gitignored .claude/settings.local.json (merged) and rebuilds .codex/hooks.json.
# Equivalent to `py tools\setup-hooks.py` on Windows.
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent

if (-not (Test-Path (Join-Path $root ".github\hooks\scripts\validate-immutable-paths.sh"))) {
    Write-Error "Hook scripts not found. Run tools/install or tools/convert -Tool shared first."
    exit 1
}

function Cmd($ps1) { "powershell -NoProfile -ExecutionPolicy Bypass -File $ps1" }

# Write UTF-8 WITHOUT a BOM. Windows PowerShell 5.1's `Set-Content -Encoding UTF8` prepends a
# BOM, which Node-based JSON parsers (Claude Code, Codex) reject — so write the bytes directly.
function Write-JsonNoBom($path, $text) {
    [System.IO.File]::WriteAllText($path, $text, (New-Object System.Text.UTF8Encoding($false)))
}

# --- Claude Code: merge a hooks block into .claude/settings.local.json ---
$claudeLocal = Join-Path $root ".claude\settings.local.json"
if (Test-Path $claudeLocal) {
    $settings = Get-Content $claudeLocal -Raw | ConvertFrom-Json
} else {
    $settings = [pscustomobject]@{}
}
$claudeHooks = [ordered]@{
    PreToolUse  = @(
        [ordered]@{ matcher = "Write|Edit|MultiEdit|NotebookEdit"; hooks = @([ordered]@{ type = "command"; command = (Cmd ".claude/hooks/validate-immutable-paths.ps1"); timeout = 10 }) },
        [ordered]@{ matcher = "Bash";                              hooks = @([ordered]@{ type = "command"; command = (Cmd ".claude/hooks/validate-bash-safety.ps1");   timeout = 10 }) }
    )
    PostToolUse = @(
        [ordered]@{ matcher = "Write|Edit|MultiEdit"; hooks = @(
            [ordered]@{ type = "command"; command = (Cmd ".claude/hooks/log-tool-use.ps1");      timeout = 15 },
            [ordered]@{ type = "command"; command = (Cmd ".claude/hooks/check-code-quality.ps1"); timeout = 30 }
        ) }
    )
}
$settings | Add-Member -NotePropertyName hooks -NotePropertyValue $claudeHooks -Force
Write-JsonNoBom $claudeLocal ($settings | ConvertTo-Json -Depth 12)

# --- Codex: rebuild .codex/hooks.json for Windows ---
$codexPath = Join-Path $root ".codex\hooks.json"
if (Test-Path (Split-Path $codexPath -Parent)) {
    function CodexCmd($ps1) { "powershell -NoProfile -ExecutionPolicy Bypass -File $ps1" }
    $codex = [ordered]@{
        _comment = "Generated by tools/setup-hooks.ps1 for Windows. Re-run after switching OS. Codex sends the same stdin JSON + exit-2 protocol; the shared .github guard scripts apply."
        hooks    = [ordered]@{
            PreToolUse  = @(
                [ordered]@{ matcher = "apply_patch|Edit|Write"; hooks = @([ordered]@{ type = "command"; command = (CodexCmd ".github/hooks/scripts/validate-immutable-paths.ps1"); timeout = 10; statusMessage = "Guarding /standards/ + /exemplars/ (read-only)" }) },
                [ordered]@{ matcher = "Bash";                   hooks = @([ordered]@{ type = "command"; command = (CodexCmd ".github/hooks/scripts/validate-bash-safety.ps1");   timeout = 10; statusMessage = "Blocking writes to immutable paths + git push/merge (human-only)" }) }
            )
            PostToolUse = @(
                [ordered]@{ matcher = "apply_patch|Edit|Write"; hooks = @(
                    [ordered]@{ type = "command"; command = (CodexCmd ".github/hooks/scripts/log-tool-use.ps1");      timeout = 15; statusMessage = "Appending to wiki/log.md" },
                    [ordered]@{ type = "command"; command = (CodexCmd ".github/hooks/scripts/check-code-quality.ps1"); timeout = 30; statusMessage = "Quality lint on written files" }
                ) }
            )
        }
    }
    Write-JsonNoBom $codexPath ($codex | ConvertTo-Json -Depth 12)
}

# --- Cursor: install .cursor/hooks.json from the staged template, rewritten for Windows ---
# Only when the Cursor adapter is present. Cursor takes a single command string per hook (no
# per-OS field, like Codex), so the .sh commands in the template are rewritten to powershell + .ps1.
$cursorDir = Join-Path $root ".cursor"
$cursorTemplate = Join-Path $root ".throughline\adapters\generated\cursor\hooks.template.json"
if ((Test-Path $cursorDir) -and (Test-Path $cursorTemplate)) {
    $raw = Get-Content $cursorTemplate -Raw
    # .github/hooks/scripts/<name>.sh  ->  powershell -NoProfile -ExecutionPolicy Bypass -File .github/hooks/scripts/<name>.ps1
    $raw = [regex]::Replace($raw, '\.github/hooks/scripts/([A-Za-z0-9._-]+)\.sh', 'powershell -NoProfile -ExecutionPolicy Bypass -File .github/hooks/scripts/$1.ps1')
    Write-JsonNoBom (Join-Path $cursorDir "hooks.json") $raw
}

# --- Antigravity: install .agents/hooks.json from the staged template, rewritten for Windows ---
$agentsDir = Join-Path $root ".agents"
$agTemplate = Join-Path $root ".throughline\adapters\generated\antigravity\hooks.template.json"
if ((Test-Path (Join-Path $root "GEMINI.md")) -and (Test-Path $agTemplate)) {
    $raw = Get-Content $agTemplate -Raw
    $raw = [regex]::Replace($raw, '\.github/hooks/scripts/([A-Za-z0-9._-]+)\.sh', 'powershell -NoProfile -ExecutionPolicy Bypass -File .github/hooks/scripts/$1.ps1')
    if (-not (Test-Path $agentsDir)) { New-Item -ItemType Directory -Path $agentsDir | Out-Null }
    Write-JsonNoBom (Join-Path $agentsDir "hooks.json") $raw
}

Write-Host "Throughline hooks wired for Windows (powershell + .ps1)."
Write-Host "  Claude Code: .claude/settings.local.json (machine-local, gitignored)"
Write-Host "  Codex:       .codex/hooks.json"
Write-Host "  Copilot:     .github/hooks/hooks.json already has a per-OS override; no action needed."
if (Test-Path (Join-Path $root ".github\hooks\copilot-cli.json")) { Write-Host "  Copilot CLI: .github/hooks/copilot-cli.json (cross-OS; no per-OS wiring needed)" }
if (Test-Path $cursorDir) { Write-Host "  Cursor:      .cursor/hooks.json (fail-open until .cursor/VERIFICATION.md passes)" }
if (Test-Path (Join-Path $agentsDir "hooks.json")) { Write-Host "  Antigravity: .agents/hooks.json (best-effort matchers until .agents/VERIFICATION.md passes)" }

# --- Kimi Code: install .kimi/config.toml from the staged template, rewritten for Windows ---
$kimiDir = Join-Path $root ".kimi"
$kimiTemplate = Join-Path $root ".throughline\adapters\generated\kimi\hooks.template.toml"
if ((Test-Path (Join-Path $kimiDir "AGENTS.md")) -and (Test-Path $kimiTemplate)) {
    $raw = Get-Content $kimiTemplate -Raw
    $raw = [regex]::Replace($raw, 'command = "\.github/hooks/scripts/([A-Za-z0-9._-]+)\.sh"', 'command = "powershell -NoProfile -ExecutionPolicy Bypass -File .github/hooks/scripts/$1.ps1"')
    if (-not (Test-Path $kimiDir)) { New-Item -ItemType Directory -Path $kimiDir | Out-Null }
    Write-JsonNoBom (Join-Path $kimiDir "config.toml") $raw
}
if (Test-Path (Join-Path $kimiDir "config.toml")) { Write-Host "  Kimi Code: .kimi/config.toml (best-effort matchers until .kimi/VERIFICATION.md passes)" }
